# Generated by Django 4.1.6 on 2023-02-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzduotis',
            name='aprasymas',
            field=models.TextField(blank=True, help_text='Aprašykite užduotį plačiau: ', null=True, verbose_name='Aprašymas'),
        ),
    ]
