# Generated by Django 4.1.6 on 2023-02-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListas', '0002_uzduotis_aprasymas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='aprasymas',
            field=models.TextField(blank=True, help_text='Aprašykite užduotį plačiau', null=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='uzduotis',
            name='sukurta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sukūrimo data:'),
        ),
    ]
