# Generated by Django 4.1.6 on 2023-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListas', '0003_alter_uzduotis_aprasymas_alter_uzduotis_sukurta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='pavadinimas',
            field=models.CharField(blank=True, help_text='Įveskite užduoties pavadinimą', max_length=200, null=True, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='uzduotis',
            name='terminas',
            field=models.DateTimeField(blank=True, help_text='Užduoties terminas', null=True, verbose_name='Įvykdyti iki:'),
        ),
    ]
